"""Repository Protocol 接口 —— Domain 层不依赖 SQLAlchemy."""
from __future__ import annotations

from typing import Protocol

from backend.domain.tasks.drama_task import DramaTask
from backend.domain.queue.queue_item import QueueItem
from backend.domain.workflow.workflow_run import WorkflowRun
from backend.domain.workflow.step_run import StepRun
from backend.domain.ledger.task_ledger import TaskLedger


class TaskRepository(Protocol):
    """DramaTask 仓储协议."""

    def add(self, task: DramaTask) -> DramaTask: ...
    def get(self, task_id: str) -> DramaTask | None: ...
    def update(self, task: DramaTask) -> DramaTask: ...
    def list_by_state(self, state: str) -> list[DramaTask]: ...


class QueueRepository(Protocol):
    """QueueItem 仓储协议."""

    def add(self, item: QueueItem) -> QueueItem: ...
    def get(self, item_id: str) -> QueueItem | None: ...
    def update(self, item: QueueItem) -> QueueItem: ...
    def list_by_state(self, state: str) -> list[QueueItem]: ...


class WorkflowRepository(Protocol):
    """WorkflowRun / StepRun 仓储协议."""

    def add_workflow(self, run: WorkflowRun) -> WorkflowRun: ...
    def get_workflow(self, run_id: str) -> WorkflowRun | None: ...
    def update_workflow(self, run: WorkflowRun) -> WorkflowRun: ...
    def add_step(self, step: StepRun) -> StepRun: ...
    def get_step(self, step_id: str) -> StepRun | None: ...
    def update_step(self, step: StepRun) -> StepRun: ...
    def list_steps_by_workflow(self, workflow_run_id: str) -> list[StepRun]: ...


class LedgerRepository(Protocol):
    """TaskLedger 仓储协议."""

    def add(self, ledger: TaskLedger) -> TaskLedger: ...
    def get(self, ledger_id: str) -> TaskLedger | None: ...
    def update(self, ledger: TaskLedger) -> TaskLedger: ...
    def list_by_task(self, task_id: str) -> list[TaskLedger]: ...
